# Generated by Django 5.1.1 on 2024-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_number',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
