# Generated by Django 5.1.1 on 2024-10-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentprofile_jop_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='jop_post',
        ),
    ]
