# Generated by Django 5.1.1 on 2024-11-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_placementevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
