# Generated by Django 5.1.1 on 2024-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_placementevent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coordinatorregistration',
            name='registration_code',
        ),
        migrations.AddField(
            model_name='coordinatorregistration',
            name='department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
