version: '3'

services:
  web:
    container_name: projectv1
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    container_name: celery-worker
    build:
      context: .
    command: celery -A project worker --loglevel=info
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app/

  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: celery -A project beat --loglevel=info
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app/
