version: '3'

services:
  web:
    container_name: projectv1
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    dns:
      - 8.8.8.8  # Add Google's public DNS

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
    dns:
      - 8.8.8.8  

  celery:
    restart: always
    build:
      context: .
    command: celery -A project worker --loglevel=info
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app/
    dns:
      - 8.8.8.8

  celery-beat:
    build:
      context: .
    command: celery -A project beat --loglevel=info
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app/
    dns:
      - 8.8.8.8      
